spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdbcurrencyexchangedb
    driver-class-name: org.postgresql.Driver
    hikari:
      username: postgres
      password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        ddl-auto: update