spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/currencyexchangedb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect

  main:
    banner-mode: off

  flyway:
    baseline-on-migrate: true